from abc import ABC, abstractmethod
from typing import AsyncGenerator, Dict, List, Optional


class AIProvider(ABC):
    """Abstract base class representing an AI Model Provider."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Provider identifier name."""
        pass

    @abstractmethod
    async def generate_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        temperature: Optional[float] = None,
        system_prompt: Optional[str] = None,
    ) -> AsyncGenerator[str, None]:
        """Stream chunks of response text generated by the AI provider.

        Args:
            messages: Conversation message list [{'role': 'user', 'content': '...'}]
            model: Model identifier
            temperature: Sampling temperature
            system_prompt: Optional system prompt to prepend or set

        Yields:
            Token text chunks
        """
        pass

    @abstractmethod
    async def list_models(self) -> List[Dict]:
        """Return list of available models from this provider."""
        pass

    @abstractmethod
    async def check_health(self) -> bool:
        """Check if the provider endpoint is healthy and responding."""
        pass

